sudo: false

language: node_js
node_js:
  - "6"

env:
  - CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/test/test_files

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run compile

script:
  - npm test --silent